### ISSUE TITLE
Unable to initialize ESAAtl80

### ISSUE THREAD

**Issue by BouwenmetStaal** [scia-garage/SciaOpenAPI_example_CSharp_simple_structure#3]
Hi

When running the script I get the error found in the picture below.

What can I do to resolve this error?

BR,
Rayaan Ajouz

![ESAAtl80](https://user-images.githubusercontent.com/48355355/61542305-8b68ad00-aa41-11e9-8e74-7a39127a97b1.PNG)

**Comment by JaroslavBroz** [comment]
Hi,
which version of SCIA Engineer 19.0 do you have? We have released a patch of 19.0. This patch contains also one enhancement of OpenAPI with C# Dispose method. Therefore, we have changed our example. Does the previous version work?

**Comment by BouwenmetStaal** [comment]
The version I use is 19.0.1219, 32 bit.

**Comment by JaroslavBroz** [comment]
Please copy ESAAtl80Extern.dll from installation from SCIA Engineer.

**Comment by MarcinTata** [comment]
Same issue here.
SCIA 19.0.2018.32,  ESAAtl80Extern.dll is both in the installation folder and  "Debug", where exe is.
![SCIAgit](https://user-images.githubusercontent.com/38285902/65383963-8dd6d400-dd1c-11e9-8cb2-51fb1cc08af6.PNG)

**Comment by PascalMartensBAM** [comment]
Hi @JaroslavBroz, is there a solution to this problem? I'm having the same issue.

Kind regards,
Pascal Martens

**Comment by jarabroz** [comment]
Hi @PascalMartensBAM,

please try the [last patch of release 19.1](https://www.scia.net/en/support/downloads/scia-engineer-19) .  The issue could be caused by the protection system. Last patch has fix.
