### ISSUE TITLE
Debugging Error

### ISSUE THREAD

**Issue by Gertwillem** [scia-garage/SciaOpenAPI_example_CSharp_simple_structure#6]
Hi,

Whenever I try to debug the program, it always loads up Scia ENgineer and then says that theres no valid license available. If i go into settings after that it shows my license and boots. But because of that there's always a next error.

How can I fix the valid license error?

**Comment by jarabroz** [comment]
Hi @Gertwillem,

it is caused with protections system. The[ last patch of release 19.1 ](https://www.scia.net/en/support/downloads/scia-engineer-19)contains fix.
